spring:
  application:
    name: sandboxapp-totp
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sandboxapp}
    username: ${DATABASE_USERNAME:totp_admin}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: totp
  flyway:
    schemas: totp
    enabled: true
    locations: classpath:db/migration/schema,classpath:db/migration/data
    validate-on-migrate: true

jwt:
  expiration_time: ${JWT_EXPIRATION_TIME:8640000}
  secret: ${JWT_SECRET:not_a_secret_and_easily_hacked_and_it_satisfies_the_requirement}