spring:
  application:
    name: sandboxapp-totp
  datasource:
    url: jdbc:postgresql://localhost:5432/sandboxapp
    username: totp_admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: totp
  flyway:
    schemas: totp
    enabled: true
    locations: classpath:db/migration/schema,classpath:db/migration/data
    validate-on-migrate: true

jwt:
  secret: ${JWT_SECRET:not_a_secret_and_easily_hacked_and_it_satisfies_the_requirement}