spring:
  application:
    name: sandboxapp-totp
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sandboxapp}
    username: ${DATABASE_USERNAME:totp_admin}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: totp
  flyway:
    schemas: totp
    enabled: true
    locations: classpath:db/migration/schema,classpath:db/migration/data
    validate-on-migrate: true
  mail:
    host: smtp.mailgun.org
    port: 587
    username: noreply@mail.sandboxapp.dev
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

jwt:
  expiration_time: ${JWT_EXPIRATION_TIME:86400}
  secret: ${JWT_SECRET:not_a_secret_and_easily_hacked_and_it_satisfies_the_requirement}

host:
  identifier: ${HOST_URL:http://localhost:4200}